export const SET_CATEGORIES = 'SET_CATEGORIES'

export const SET_COMMENTS = 'SET_COMMENTS'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'

export const OPEN_COMMENTS_SIDE_BAR = 'OPEN_COMMENTS_SIDE_BAR'
export const CLOSE_COMMENTS_SIDE_BAR = 'CLOSE_COMMENTS_SIDE_BAR'