export const ADD_POST = 'ADD_POST'
export const REMOVE_POST = 'REMOVE_POST'
export const SET_POSTS_ORDER = 'SET_POSTS_ORDER'

export const SET_CATEGORIES = 'SET_CATEGORIES'
export const LOADING_CATEGORIES = 'LOADING_CATEGORIES'

export const ADD_COMMENTS = 'ADD_COMMENTS'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'
export const LOADING_COMMENTS = 'LOADING_COMMENTS'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'